# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  dotnetcoreindocker:
    image: dotnetcoreindocker
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000

  volumes:
        - /host-folder-path:/container-folder-path #
      
#Volume mounts#
#By default, the Docker extension does not do any volume mounting for debugging components. 
#There's no need for it in .NET Core or Node.js, since the required components are built into the runtime. 
#If your app requires volume mounts, specify them by using the volumes tag in the docker-compose*.yml files 
# https://code.visualstudio.com/docs/containers/docker-compose  

#.........................................................................................................
# The Compose file provides a way to document and configure all of the application’s service dependencies
# (databases, queues, caches, web service APIs, etc). Using the Compose command line tool you can create and start one or more containers for each dependency with a single command 
#(docker-compose up).
#https://docs.docker.com/compose/
#Automated testing environments: 
  #$ docker-compose up -d
  #$ ./run_tests
  #$ docker-compose down